# Generated by Django 4.2.7 on 2023-11-20 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=32)),
                ('id_produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produto')),
            ],
        ),
    ]
