[tool.poetry]
name = "development"
version = "0.0.1"
description = ""
authors = ["LiamMartingo42","liammartingo@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
