# Generated by Django 4.2.7 on 2023-11-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField(max_length=50)),
            ],
        ),
    ]
